version: '3.8'

services:
  markitdown-web:
    build: .
    container_name: markitdown-web-service
    ports:
      - "8490:8490"
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    environment:
      - TZ=America/Asuncion
