version: '3.8'

services:
  doctomd:
    build: .
    container_name: doctomd-service
    ports:
      - "8490:8490"
    volumes:
      - ./output:/app/output
    restart: unless-stopped
    environment:
      - TZ=America/Asuncion
